### ISSUE TITLE
Great work!

### ISSUE THREAD

**Issue by alexec** [tourdedave/the-internet#18]
Hi, 

Excellent stuff. I can see me writing against this. May put thing into two groups?

* Standard HTML
* jQuery (or Rich Javascript?) and then you can added progress bars etc.

Alex

**Comment by tourdedave** [comment]
Hey Alex,

Thanks for the kind words!

The naming of the examples should speak for themselves (e.g., on [the homepage](http://the-internet.herokuapp.com/)). Adding an artificial grouping would add undue complexity. The goal of this project is to be as simple as possible.

If you're looking for something with progress bars, take a look at the [Dynamic Loading example](http://the-internet.herokuapp.com/dynamic_loading).


Cheers,
Dave H
