### ISSUE TITLE
Response text when checkbox is checked

### ISSUE THREAD

**Issue by wilsonmar** [tourdedave/the-internet#21]
Within http://the-internet.herokuapp.com/checkboxes, how about a response appears so that the test script can validate whether an action was recognized?

**Comment by tourdedave** [comment]
I just released an updated version of /checkboxes (in 0.45.1) that dynamically updates each input field to add or remove a `checked` attribute depending on its state (e.g., checked or not checked).

This will make it easier to test when the page has been updated.

If you're curious on how this comes together in a test with Selenium, I've written about it [here](http://elementalselenium.com/tips/45-checkboxes).
