### ISSUE TITLE
It doesn't run with rakeup

### ISSUE THREAD

**Issue by isakib** [tourdedave/the-internet#23]
I've tried all possible ways to run with rakeup. That found, it runs with "ruby server.rb" to run the project on local server.

**Comment by tourdedave** [comment]
`ruby server.rb` is one way to run it. I believe the command you're looking for is `rackup` (e.g., `bundle exec rackup` to be precise). This works on my local development environment. Try it and let me know it's what you're looking for.

To be clear -- there is no `rake` task to launch the server. If you do a `rake -T` you'll see the following output:

```sh
rake gen_docs    # Generate docs
rake release     # Pushes tags and code to master, develop, and heroku
rake rm_uploads  # Cleanup uploaded files
```

These tasks are to handle the administrivia of the library (e.g., updating documentation, releasing the software to GitHub and Heroku, etc.).

**Comment by isakib** [comment]
Thanks. I was following readme.md file. So, I found ```bundle exec rackup``` does the job nicely.

**Comment by tourdedave** [comment]
Ah, I thought you were trying `rakeup` (which isn't a valid command).

**Comment by isakib** [comment]
Then, could you please update Start the server: => https://github.com/tourdedave/the-internet with ```bundle exec rackup``` instead of ```rakeup```

**Comment by tourdedave** [comment]
There's nothing to update since README.md already states `rackup`.

**Comment by isakib** [comment]
Thanks a lot @tourdedave for your support.
