### ISSUE TITLE
/value on /dropdown's select element returns empty - but only in Firefox

### ISSUE THREAD

**Issue by andrew-fowler** [tourdedave/the-internet#28]
Hi there,

I'm trialling webdriverio against the site, and on the dropdown page when I call getValue() on the element (after selecting the first option), I'm getting empty returned - but only on Firefox.  On Chrome and IE it works as expected.  I thought it might be a race condition, but a 1sec pause doesn't change the result.

API call:
```
COMMAND
GET element/0/attribute/value

PARAMETERS
{}

RESPONSE
=>
```

Test: https://github.com/andrew-fowler/webdriverio-theinternet/blob/master/test/specs/dropdown/dropdown.spec.js#L12

Example Sauce run: https://saucelabs.com/beta/tests/4e608f911d2c4817870135ad76e7b109

I was assuming that I was doing something wrong, but I'm struggling to see it.

Thanks,
Andrew

**Comment by tourdedave** [comment]
I cloned your repo and ran the tests. This appears to be working (see my recent job [here](https://saucelabs.com/beta/tests/8018417b7b3f44b0a6cbe6df055e0a42/commands#12)). Not sure what would have caused it on my end since it is a vanilla dropdown form using standard HTML markup (no JS).
