### ISSUE TITLE
there is a the-internet docker image

### ISSUE THREAD

**Issue by timrsfo** [tourdedave/the-internet#29]
I've been trying to get upto speed with docker and testing and I found [gprestes/the-internet](https://hub.docker.com/r/gprestes/the-internet/) - maybe a link could be added to your readme

**Comment by gprestes** [comment]
Thank you @timrsfo for recommending the image I created. If you have any suggestion/improvement please send them as Issues/PR's in the [image repository](https://github.com/gprestes/the-internet-docker).

**Comment by anyone-can-test** [comment]
thank you very much

**Comment by tourdedave** [comment]
Added to the readme in commit 083290e4f6a2a15592bdffc65731de5be1d71b1b
